<a href="https://colab.research.google.com/github/s-rafia/Samsung-Innovation-Campus-AI-Training/blob/main/3D-Array_and_Dot_Product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3D Array

In [ ]:
import numpy as np
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

# reshape

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Indexing

In [ ]:
a3 = np.arange(12).reshape(3,4)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3[1,0]

np.int64(4)

In [ ]:
a3[1,2]

np.int64(6)

In [ ]:
a3[1,1]

np.int64(0)

In [ ]:
a3[0,0]

np.int64(0)

In [ ]:
a3[2,0]

np.int64(8)

In [ ]:
a3[0,2]

np.int64(2)

In [ ]:
a3[2,2]

np.int64(10)

# Indexing-Matrix 3D

In [ ]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

# Slicing

In [ ]:
a3[0]

array([[0, 1],
       [2, 3]])

In [ ]:
a3[0,1]

array([2, 3])

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a3[:,0,0]
# : takes all blocks
# 0 takes first row in each block
# 0 take first column in that row

array([0, 4])

In [ ]:
a3[:,:,1]
# : takes all blocks
# : takes all rows
# 1 secong column

array([[1, 3],
       [5, 7]])

# Linear Algebra - Dot Product

Metrix Multiplication: Row x Column rule

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
c = np.array([[2,0],[1,3]])
d = np.array([[1,2],[3,4]])
print(np.dot(c,d))

[[ 2  4]
 [10 14]]


In [ ]:
c1 = np.arange(8).reshape(2,2,2)
c1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
d1 = np.arange(8).reshape(2,2,2)
d1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(np.dot(c1,d1))

[[[[ 2  3]
   [ 6  7]]

  [[ 6 11]
   [26 31]]]


 [[[10 19]
   [46 55]]

  [[14 27]
   [66 79]]]]


# Iteration

In [ ]:
a = np.arange(6).reshape(2,3)

for i in a:
  print(i)

[0 1 2]
[3 4 5]


nditer:
Prints each element individually

In [ ]:
for i in np.nditer(a):
  print(i)

0
1
2
3
4
5


# Transpose

In [ ]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
c.T

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

# Ravel

Flattens into 1D array

In [ ]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [ ]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

hstack - add columns

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


vstack - add rows

In [ ]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Class Practice

Make 1D array

In [ ]:
a1d = np.array([1,2,3])
a1d

array([1, 2, 3])

Make 2D Array

In [ ]:
b2d = np.array([[1,2,3],[4,5,6]])
b2d

array([[1, 2, 3],
       [4, 5, 6]])

Make 2 Matrix (3D)

In [ ]:
c3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
d3d = np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
d3d

array([[[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

Do the following operations:
1. Dot Product

In [ ]:
print(np.dot(c3d,d3d))

[[[[ 31  34]
   [ 43  46]]

  [[ 71  78]
   [ 99 106]]]


 [[[111 122]
   [155 166]]

  [[151 166]
   [211 226]]]]


2. Transpose

In [ ]:
c3d.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

3. Ravel

In [ ]:
c3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

4. Slicing

In [ ]:
d3d[0]

array([[ 9, 10],
       [11, 12]])

In [ ]:
c3d[1]

array([[5, 6],
       [7, 8]])

5. Shape, size, sizeitem, ndim

In [ ]:
c3d.shape

(2, 2, 2)

In [ ]:
c3d.size

8

In [ ]:
c3d.itemsize

8

In [ ]:
c3d.ndim

3

6. hstack - add columns
vstack - add rows

In [ ]:
print(np.hstack(c3d))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.vstack(c3d))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
