<a href="https://colab.research.google.com/github/s-rafia/Samsung-Innovation-Campus-AI-Training/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import NumPy**

In [ ]:
import numpy as np

# **Creating Arrays**

1. 1D Array

In [ ]:
a = np.array([1, 2, 3,])
a

array([1, 2, 3])

In [ ]:
a.ndim

1

2. 2D Array

In [ ]:
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.ndim

2

3. 3D Array

In [ ]:
c = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# **np.arange and reshape**

1. arange

In [ ]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

2. reshape

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. reshape-Error

In [ ]:
np.arange(167).reshape(2, 2, 2, 2)

ValueError: cannot reshape array of size 167 into shape (2,2,2,2)

# **Array Attributes**

In [ ]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

1. ndim

In [ ]:
a3.ndim

3

2. shape

In [ ]:
a3.shape

(2, 2, 2)

3. size

In [ ]:
a3.size

8

4. itemsize

In [ ]:
a3.itemsize

8

# **Indexing**

In [ ]:
a3 = np.arange(12).reshape(3,4)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3[1,0]

np.int64(4)

In [ ]:
print(a3[1,1],"," ,a3[0,0],"," ,a3[2,0],"," ,a3[0,2],"," ,a3[2,2])

5 , 0 , 8 , 2 , 10


# **Indexing-Matrix 3D**

In [ ]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[1,1,0]

np.int64(6)

# **Slicing**

In [ ]:
a3[0]

array([[0, 1],
       [2, 3]])

In [ ]:
a3[0,1]

array([2, 3])

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a3[:, 0, 0]

array([0, 4])

In [ ]:
a3[:, :, 1]

array([[1, 3],
       [5, 7]])

# **Linear Algebara - Dot Product**

In [ ]:
a = np.array([[1, 2],
             [3, 4]])

b = np.array([[5,6],
              [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
c = np.array([[2, 0],
              [1, 3]])

d = np.array([[1, 2],
              [3, 4]])
print(np.dot(c,d))

[[ 2  4]
 [10 14]]


# **Iteration**

In [ ]:
a = np.arange(6).reshape(2,3)

for i in a:
  print(i)

[0 1 2]
[3 4 5]


nditer - Prints each element individually

In [ ]:
for i in np.nditer(a):
  print(i)

0
1
2
3
4
5


# **Transpose**

In [ ]:
a3.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

# **Ravel**

In [ ]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

# **Stacking**

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6],[7,8]])

print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
